AllCops:
  Exclude:
    - vendor/**/**
    - bin/**



CollectionMethods:
  # Mapping from undesired method to desired_method
  # e.g. to use `detect` over `find`:
  #
  # CollectionMethods:
  #   PreferredMethods:
  #     find: detect
  PreferredMethods:
    map: 'collect'
    map!: 'collect!'
    reduce: 'inject'
    find: 'detect'
    find_all: 'select'

StringLiterals:
  EnforcedStyle: double_quotes
